//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int EmpId { get; set; }
        [Required]
        public string EmployeeName { get; set; }
        [Required]
        public decimal Salary { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SkillId { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid email format.")]
        public string Email { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
